// Generate scripts/arena-probe.js from src/platform/arenaContract.ts.
//
// The probe is pasteable console JS (no imports). Editing it by hand is how
// Battle detection drifted off production in #21. This file is the only
// writer; CI runs `npm run probe:check`.
//
//   npm run gen:probe
//   npm run probe:check
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";
import prettier from "prettier";
import {
	ACTIVE_MODE_SELECTOR,
	ASSISTANT_MESSAGE_SELECTOR,
	BATTLE_MODE_LABEL,
	BATTLE_VOTE_PATTERNS,
	BATTLE_VOTE_QUORUM,
	CONTROL_SELECTOR,
	HISTORY_LINK_SELECTOR,
	MODE_CONTROL_SELECTOR,
	SCROLL_CONTAINER_SELECTORS,
	SIDEBAR_CONTAINER_SELECTOR,
	SIDEBAR_MENU_SELECTOR,
	SIDEBAR_SELECTOR,
	SIDEBAR_WRAPPER_SELECTOR,
	USER_MESSAGE_SELECTOR,
} from "../src/platform/arenaContract.ts";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const PROBE_PATH = path.join(ROOT, "scripts/arena-probe.js");

const CONTRACT = {
	activeModeSelector: ACTIVE_MODE_SELECTOR,
	modeControlSelector: MODE_CONTROL_SELECTOR,
	controlSelector: CONTROL_SELECTOR,
	battleModeLabel: BATTLE_MODE_LABEL.source,
	battleVotePatterns: BATTLE_VOTE_PATTERNS.map((p) => p.source),
	battleVoteQuorum: BATTLE_VOTE_QUORUM,
	userMessageSelector: USER_MESSAGE_SELECTOR,
	assistantMessageSelector: ASSISTANT_MESSAGE_SELECTOR,
	scrollContainerSelectors: [...SCROLL_CONTAINER_SELECTORS],
	sidebarSelector: SIDEBAR_SELECTOR,
	sidebarContainerSelector: SIDEBAR_CONTAINER_SELECTOR,
	sidebarMenuSelector: SIDEBAR_MENU_SELECTOR,
	sidebarWrapperSelector: SIDEBAR_WRAPPER_SELECTOR,
	historyLinkSelector: HISTORY_LINK_SELECTOR,
	hostId: "__edge_ai_sidebar_host",
};

function generate(): string {
	const contractLit = JSON.stringify(CONTRACT, null, "\t");
	return `/* Arena Sidebar 真站结构探针
 * GENERATED by scripts/gen-probe.ts — do not edit.
 * npm run gen:probe
 *
 * 只读：不点击、不写 DOM、不发请求、不碰存储。
 * 登录 arena.ai → F12 → Console → 粘贴本文件 → 回车。
 * 把输出里的 snapshot 存成 tests/__fixtures__/probes/<id>.json，CI 会重放。
 */
(() => {
	const CONTRACT = ${contractLit};

	const cap = (s, n) =>
		(s === null || s === undefined ? "" : String(s))
			.replace(/\\s+/g, " ")
			.trim()
			.slice(0, n);
	const cls = (el) =>
		cap(typeof el.className === "string" ? el.className : "", 100);
	const uniq = (arr) => [...new Set(arr)];

	const BATTLE_LABEL = new RegExp(CONTRACT.battleModeLabel, "i");
	const VOTE_PATTERNS = CONTRACT.battleVotePatterns.map((s) => new RegExp(s));

	function detectBattleMode(root) {
		const tabs = root.querySelectorAll(CONTRACT.activeModeSelector);
		for (const tab of tabs) {
			if (BATTLE_LABEL.test(tab.textContent || "")) return true;
		}
		const seen = new Set();
		const buttons = root.querySelectorAll(CONTRACT.controlSelector);
		for (const btn of buttons) {
			const text = (btn.textContent || "").toLowerCase();
			VOTE_PATTERNS.forEach((pattern, i) => {
				if (pattern.test(text)) seen.add(i);
			});
			if (seen.size >= CONTRACT.battleVoteQuorum) return true;
		}
		return false;
	}

	function scrollKind() {
		if (document.querySelector(CONTRACT.scrollContainerSelectors[0]))
			return "radix";
		if (document.querySelector(CONTRACT.scrollContainerSelectors[2]))
			return "legacy-and";
		if (document.querySelector(CONTRACT.scrollContainerSelectors[1]))
			return "overscroll";
		return "none";
	}

	function sidebarKind() {
		if (document.querySelector(CONTRACT.sidebarSelector)) return "shadcn";
		if (document.querySelector(CONTRACT.sidebarWrapperSelector))
			return "legacy";
		return "none";
	}

	function sidebarExpect() {
		const root =
			document.querySelector(CONTRACT.sidebarSelector) ||
			document.querySelector(CONTRACT.sidebarWrapperSelector);
		if (!root) return "sidebar";
		if (root.querySelector(CONTRACT.sidebarContainerSelector)) return "ok";
		if (root.querySelector(CONTRACT.sidebarMenuSelector)) return "ok";
		return "container";
	}

	const out = {
		probe: "arena-probe-v2",
		url: location.href,
		title: document.title,
		inIframe: window !== window.top,
		time: new Date().toISOString(),
	};

	try {
		out.tabs = [...document.querySelectorAll(CONTRACT.modeControlSelector)]
			.slice(0, 20)
			.map((el) => ({
				tag: el.tagName,
				text: cap(el.textContent, 40),
				role: el.getAttribute("role") || "",
				ariaSelected: el.getAttribute("aria-selected") || "",
				ariaPressed: el.getAttribute("aria-pressed") || "",
				dataState: el.getAttribute("data-state") || "",
				testid: el.getAttribute("data-testid") || "",
				cls: cls(el),
			}));

		const buttons = [...document.querySelectorAll(CONTRACT.controlSelector)];
		out.buttonCount = buttons.length;
		out.buttons = buttons
			.filter(
				(b) =>
					cap(b.textContent, 1) !== "" ||
					(b.getAttribute("aria-label") || "") !== "",
			)
			.slice(0, 120)
			.map((b) => ({
				text: cap(b.textContent, 60),
				ariaLabel: cap(b.getAttribute("aria-label"), 60),
				testid: cap(b.getAttribute("data-testid"), 60),
				cls: cls(b),
			}));

		const battle = detectBattleMode(document);
		const signal2 = VOTE_PATTERNS.map((p, i) => ({
			pattern: String(p),
			hit: buttons.some((b) => p.test((b.textContent || "").toLowerCase())),
			hitTexts:
				i === 2
					? undefined
					: uniq(
							buttons
								.filter((b) => p.test((b.textContent || "").toLowerCase()))
								.map((b) => cap(b.textContent, 40)),
						).slice(0, 5),
		}));
		let signal1 = null;
		for (const tab of document.querySelectorAll(CONTRACT.activeModeSelector)) {
			if (BATTLE_LABEL.test(tab.textContent || "")) {
				signal1 = cap(tab.textContent, 40);
				break;
			}
		}
		out.battleDetect = {
			signal1ActiveBattleTab: signal1,
			signal2VotePatterns: signal2,
			quorumHits: signal2.filter((s) => s.hit).length,
			quorumNeeded: CONTRACT.battleVoteQuorum,
			verdict: battle,
		};

		const users = [...document.querySelectorAll(CONTRACT.userMessageSelector)];
		const assts = [
			...document.querySelectorAll(CONTRACT.assistantMessageSelector),
		];
		out.extract = {
			userSelHits: users.length,
			asstSelHits: assts.length,
			userSample: users[0]
				? {
						tag: users[0].tagName,
						text: cap(users[0].textContent, 60),
						cls: cls(users[0]),
						width: Math.round(users[0].getBoundingClientRect().width),
					}
				: null,
			asstSample: assts[0]
				? {
						tag: assts[0].tagName,
						text: cap(assts[0].textContent, 60),
						cls: cls(assts[0]),
					}
				: null,
		};

		const host = document.getElementById(CONTRACT.hostId);
		out.extension = {
			hostPresent: !!host,
			hasShadow: !!host?.shadowRoot,
			fabPresent: !!host?.shadowRoot?.querySelector(".fab"),
			battleNoticeShown: host?.shadowRoot
				? cap(host.shadowRoot.textContent, 400).includes("Battle mode")
				: false,
			note: "host uses closed shadow — hasShadow/fabPresent are false from page JS even when the extension is alive",
		};

		out.scrollContainerFound = scrollKind() !== "none";
		out.historyLinkCount = document.querySelectorAll(
			CONTRACT.historyLinkSelector,
		).length;

		const voteButtons = uniq(
			buttons
				.map((b) => cap(b.textContent, 40))
				.filter((t) =>
					VOTE_PATTERNS.some((p) => p.test(t.toLowerCase())),
				),
		).slice(0, 8);

		const messages = [];
		const take = (els, role, n) => {
			for (const el of els.slice(0, n)) {
				messages.push({
					role,
					text: cap(el.textContent, 80),
					width: Math.round(el.getBoundingClientRect().width) || undefined,
				});
			}
		};
		take(users, "user", 2);
		take(assts, "assistant", 2);

		let page = "direct";
		if (battle) page = "battle";
		else if (/\\/agent/i.test(location.pathname)) page = "agent";
		else if (location.pathname === "/" || location.pathname === "")
			page = "home";

		out.snapshot = {
			schema: 1,
			id: (location.pathname.replace(/[^a-z0-9]+/gi, "-") || "arena")
				.replace(/^-|-$/g, "")
				.slice(0, 60),
			source: "live probe " + out.time,
			capturedAt: out.time.slice(0, 10),
			page,
			url: location.origin + location.pathname,
			expect: {
				battle,
				sidebar: sidebarExpect(),
				scrollFound: out.scrollContainerFound,
				extractUserHitsMin: users.length > 0 ? users.length : undefined,
				extractAsstHitsMin: assts.length > 0 ? assts.length : undefined,
				extractKeptMin: undefined,
			},
			dom: {
				sidebar: sidebarKind(),
				scroll: scrollKind(),
				historyLinks: [...document.querySelectorAll(CONTRACT.historyLinkSelector)]
					.map((a) => a.getAttribute("href") || "")
					.filter(Boolean)
					.slice(0, 5),
				modeButtons: (out.tabs || []).map((t) => ({
					text: t.text,
					role: t.role || undefined,
					ariaSelected: t.ariaSelected || undefined,
					ariaPressed: t.ariaPressed || undefined,
					dataState: t.dataState || undefined,
				})),
				voteButtons,
				messages,
			},
		};

		console.log(
			"%c=== ARENA PROBE v2 · " + out.url + " ===",
			"font-weight:bold",
		);
		console.log(
			"Battle检测: verdict=" +
				out.battleDetect.verdict +
				"（tab信号=" +
				JSON.stringify(out.battleDetect.signal1ActiveBattleTab) +
				" 投票quorum=" +
				out.battleDetect.quorumHits +
				"/" +
				CONTRACT.battleVoteQuorum +
				"）",
		);
		console.log(
			"提取器: user=" +
				out.extract.userSelHits +
				" asst=" +
				out.extract.asstSelHits +
				" · 扩展host=" +
				out.extension.hostPresent +
				" FAB=" +
				out.extension.fabPresent +
				"（closed shadow 下 FAB 读不到属正常） · 滚动=" +
				scrollKind() +
				" 侧栏=" +
				sidebarKind(),
		);
		const json = JSON.stringify(out, null, 1);
		console.log(json);
		let copied = false;
		try {
			if (typeof copy === "function") {
				copy(out.snapshot);
				copied = true;
			}
		} catch {
			/* DevTools copy() missing */
		}
		if (!copied && navigator.clipboard?.writeText) {
			navigator.clipboard
				.writeText(JSON.stringify(out.snapshot, null, 2))
				.then(() =>
					console.log(
						"%c✔ snapshot 已复制。存成 tests/__fixtures__/probes/<id>.json",
						"color:green",
					),
				)
				.catch(() =>
					console.log(
						"%c剪贴板被拦，手动复制输出里的 snapshot 字段",
						"color:orange",
					),
				);
		} else if (copied) {
			console.log(
				"%c✔ snapshot 已复制。存成 tests/__fixtures__/probes/<id>.json",
				"color:green",
			);
		}
	} catch (e) {
		console.log(
			"%c探针出错（把这行连同 URL 发我）: " + ((e && e.message) || e),
			"color:red",
		);
		console.log(JSON.stringify(out, null, 1));
	}
})();
`;
}

async function format(source: string): Promise<string> {
	const cfg = await prettier.resolveConfig(PROBE_PATH);
	return prettier.format(source, { ...cfg, filepath: PROBE_PATH });
}

async function main() {
	const check = process.argv.includes("--check");
	const next = await format(generate());
	if (check) {
		const prev = readFileSync(PROBE_PATH, "utf8");
		if (prev !== next) {
			console.error("scripts/arena-probe.js is stale. Run npm run gen:probe");
			process.exit(1);
		}
		console.log("scripts/arena-probe.js is up to date");
		return;
	}
	writeFileSync(PROBE_PATH, next);
	console.log("wrote", path.relative(ROOT, PROBE_PATH));
}

main().catch((err) => {
	console.error(err);
	process.exit(1);
});
